---
title: "Introduction to Tidyverse"
author: "Narayanan Raghupathy"
date: "1/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load_libraries}
library(ggplot2)
library(dplyr)
```

```{r load_data}
gapminder = read.csv("~/Desktop/gapminder/data/gapminder-FiveYearData.csv",stringsAsFactors = FALSE)
head(gapminder)
```
```{r filter_verb}
# Filter the gapminder dataset for the year 1957
head(gapminder %>% filter(year==1957))
# Filter for China in 2002
head(gapminder %>% filter(country=="China",year==2002))
```

```{r arrange_verb}
# Sort in ascending order of lifeExp
head(gapminder %>% arrange(lifeExp))
  
# Sort in descending order of lifeExp
head(gapminder %>% arrange(desc(lifeExp)))
```
```{r filter-arrange}
# Filter for the year 1957, then arrange in descending order of population
head(gapminder %>% filter(year==1957) %>% arrange(desc(pop)))

```
```{r mutate_verb}
# Use mutate to change lifeExp to be in months
head(gapminder %>% mutate(lifeExp=lifeExp*12))

# Use mutate to create a new column called lifeExpMonths
head(gapminder %>% mutate(lifeExpMonths=lifeExp*12))

```
```{r filter_mutate_arrange}
# Filter, mutate, and arrange the gapminder dataset
gapminder %>% filter(year==2007) %>% mutate(lifeExpMonths =12*lifeExp) %>% arrange(desc(lifeExpMonths))
```
```{r with_ggplot}
# Create gapminder_1952
gapminder_1952 <- gapminder %>%
  filter(year == 1952)
# Change to put pop on the x-axis and gdpPercap on the y-axis
ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
  geom_point()
# Create a scatter plot with pop on the x-axis and lifeExp on the y-axis
ggplot(gapminder_1952,aes(x=pop,y=lifeExp))+geom_point()
# Change this plot to put the x-axis on a log scale
ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) +
  geom_point()+scale_x_log10()
# Scatter plot comparing pop and gdpPercap, with both axes on a log scale
ggplot(gapminder_1952,aes(x=pop,y=gdpPercap))+geom_point()+scale_x_log10()+scale_y_log10()

# Scatter plot comparing pop and lifeExp, with color representing continent
ggplot(gapminder_1952,aes(x=pop,y=lifeExp,color=continent))+geom_point() +scale_x_log10()

# Add the size aesthetic to represent a country's gdpPercap
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent,size=gdpPercap)) +
  geom_point() +
  scale_x_log10()
# Scatter plot comparing pop and lifeExp, faceted by continent
ggplot(gapminder_1952,aes(x=pop,y=lifeExp))+geom_point()+facet_wrap(~continent)+scale_x_log10()
# Scatter plot comparing gdpPercap and lifeExp, with color representing continent
# and size representing population, faceted by year
ggplot(gapminder,aes(x=gdpPercap,y=lifeExp,color=continent,size=pop))+geom_point()+facet_wrap(~year)+scale_x_log10()
```
```{r summarize}
# Summarize to find the median life expectancy
gapminder %>% summarize(medianLifeExp=median(lifeExp))
# Filter for 1957 then summarize the median life expectancy
gapminder %>% filter(year==1957) %>% summarize(medianLifeExp=median(lifeExp))
# Filter for 1957 then summarize the median life expectancy and the maximum GDP per capita
gapminder %>% filter(year==1957) %>% summarize(medianLifeExp=median(lifeExp),maxGdpPercap=max(gdpPercap))
```

```{r group_by}
# Find median life expectancy and maximum GDP per capita in each year
gapminder %>% group_by(year) %>% summarize(medianLifeExp=median(lifeExp),maxGdpPercap=max(gdpPercap))

# Find median life expectancy and maximum GDP per capita in each continent in 1957
gapminder %>% group_by(continent,year) %>% summarize(medianLifeExp=median(lifeExp),maxGdpPercap=max(gdpPercap))

# Find median life expectancy and maximum GDP per capita in each year/continent combination
gapminder %>% group_by(continent,year) %>% summarize(medianLifeExp=median(lifeExp),maxGdpPercap=max(gdpPercap))

by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp),
            maxGdpPercap = max(gdpPercap))

# Create a scatter plot showing the change in medianLifeExp over time
ggplot(by_year,aes(x=year,y=medianLifeExp)) + geom_point() +expand_limits(y=0)

# Summarize medianGdpPercap within each continent within each year: by_year_continent
by_year_continent = gapminder %>% group_by(year,continent) %>% summarize(medianGdpPercap=median(gdpPercap))

# Plot the change in medianGdpPercap in each continent over time
ggplot(by_year_continent, aes(x=year,y=medianGdpPercap, color=continent))+geom_point()+expand_limits(y=0)

# Summarize the median GDP and median life expectancy per continent in 2007
by_continent_2007=gapminder %>% filter(year==2007) %>% group_by(continent) %>% summarize(medianLifeExp=median(lifeExp),medianGdpPercap=median(gdpPercap))

# Use a scatter plot to compare the median GDP and median life expectancy
ggplot(by_continent_2007,aes(x=medianGdpPercap,y=medianLifeExp,color=continent))+geom_point()
```

```{r line_plots}
# Summarize the median GDP and median life expectancy per continent in 2007
by_continent_2007=gapminder %>% filter(year==2007) %>% group_by(continent) %>% summarize(medianLifeExp=median(lifeExp),medianGdpPercap=median(gdpPercap))

# Use a scatter plot to compare the median GDP and median life expectancy
ggplot(by_continent_2007,aes(x=medianGdpPercap,y=medianLifeExp,color=continent))+geom_point()

# Summarize the median gdpPercap by year & continent, save as by_year_continent
by_year_continent <- gapminder %>% group_by(year, continent) %>% summarize(medianGdpPercap=median(gdpPercap))

# Create a line plot showing the change in medianGdpPercap by continent over time
ggplot(by_year_continent,aes(x=year,y=medianGdpPercap, color=continent))+geom_line()+expand_limits(y=0)
```
```{r}
# Summarize the median gdpPercap by year and continent in 1952
by_continent= gapminder %>% filter(year==1952)%>% group_by(continent) %>% summarize(medianGdpPercap=median(gdpPercap))

# Create a bar plot showing medianGdp by continent
ggplot(by_continent,aes(x=continent,y=medianGdpPercap))+geom_col() 

# Filter for observations in the Oceania continent in 1952
oceania_1952 = gapminder %>% filter(continent=="Oceania",year==1952)
# Create a bar plot of gdpPerCap by country
ggplot(oceania_1952,aes(x=country,y=gdpPercap)) + geom_col()
```
```{r histograms}
gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Create a histogram of population (pop)
ggplot(gapminder_1952,aes(x=pop))+geom_histogram()

# Create a histogram of population (pop), with x on a log scale
ggplot(gapminder_1952,aes(x=pop))+geom_histogram()+scale_x_log10()
```
```{r boxplots}
gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Create a boxplot comparing gdpPercap among continents
ggplot(gapminder_1952,aes(x=continent,y=gdpPercap))+geom_boxplot()+geom_point()+scale_y_log10()

# Add a title to this graph: "Comparing GDP per capita across continents"
ggplot(gapminder_1952, aes(x = continent, y = gdpPercap)) +
  geom_boxplot() +
  scale_y_log10() +ggtitle("Comparing GDP per capita across continents")
```













